services:
#  app:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always